spring:
  application:
    name: cherrish

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:cherrish}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

server:
  port: ${SERVER_PORT:8080}
