spring:
  application:
    name: cherrish

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include:
      - db
      - openai
      - auth
      - redis

  config:
    import: optional:file:.env[.properties]

server:
  port: ${SERVER_PORT:8080}
